export const MOBILE_TWITCH_SCOPES = [
  "chat:read",
  "user:read:chat",
  "user:write:chat",
  "user:read:emotes",
  "user:manage:blocked_users",
  "user:read:moderated_channels",
  "moderator:manage:banned_users",
  "moderator:manage:chat_messages",
  "moderator:manage:chat_settings",
  "moderator:read:chat_settings",
  "moderator:manage:automod",
  "channel:read:polls",
  "channel:manage:polls",
  "channel:read:predictions",
  "channel:manage:predictions",
  "moderator:read:unban_requests",
  "moderator:manage:unban_requests",
  "moderation:read",
  "channel:manage:moderators",
  "channel:read:vips",
  "channel:manage:vips",
] as const;
