export const DEFAULT_MOBILE_TWITCH_SCOPES = [
  "chat:read",
  "user:read:chat",
  "user:write:chat",
  "user:read:emotes",
  "user:manage:blocked_users",
  "user:read:moderated_channels",
  "moderator:manage:banned_users",
  "moderator:manage:chat_messages",
  "moderator:manage:chat_settings",
  "moderator:read:chat_settings",
  "moderator:manage:automod",
  "channel:read:polls",
  "channel:manage:polls",
  "channel:read:predictions",
  "channel:manage:predictions",
  "moderator:read:unban_requests",
  "moderator:manage:unban_requests",
  "moderation:read",
  "channel:manage:moderators",
  "channel:read:vips",
  "channel:manage:vips",
] as const;

export const MOBILE_TWITCH_SCOPES = [
  ...DEFAULT_MOBILE_TWITCH_SCOPES,
  "channel:read:subscriptions",
  "bits:read",
  "channel:manage:broadcast",
  "channel:manage:raids",
  "channel:read:redemptions",
  "channel:manage:redemptions",
  "moderator:read:shield_mode",
  "moderator:manage:shield_mode",
  "moderator:read:automod_settings",
  "moderator:manage:automod_settings",
  "moderator:read:blocked_terms",
  "moderator:manage:blocked_terms",
  "moderator:read:chatters",
  "moderator:read:followers",
  "moderator:read:suspicious_users",
  "moderator:manage:suspicious_users",
  "user:read:whispers",
  "user:manage:whispers",
  "moderator:read:banned_users",
  "moderator:read:chat_messages",
  "moderator:read:warnings",
  "moderator:read:moderators",
  "moderator:read:vips",
] as const;
