/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './start-root'
import { Route as featuresShellRoutesStartLayoutRouteImport } from './../features/shell/routes/start-layout'
import { Route as featuresDiscoveryRoutesStartHomeRouteImport } from './../features/discovery/routes/start-home'
import { Route as featuresDiscoveryRoutesStartCategoriesRouteImport } from './../features/discovery/routes/start-categories'
import { Route as featuresMediaLibraryRoutesStartDownloadsRouteImport } from './../features/media-library/routes/start-downloads'
import { Route as featuresDiscoveryRoutesStartFollowingRouteImport } from './../features/discovery/routes/start-following'
import { Route as featuresMediaLibraryRoutesStartHistoryRouteImport } from './../features/media-library/routes/start-history'
import { Route as featuresModerationRoutesStartModRouteImport } from './../features/moderation/routes/start-mod'
import { Route as featuresMultistreamRoutesStartMultistreamRouteImport } from './../features/multistream/routes/start-multistream'
import { Route as featuresDiscoveryRoutesStartSearchRouteImport } from './../features/discovery/routes/start-search'
import { Route as featuresSettingsRoutesStartSettingsRouteImport } from './../features/settings/routes/start-settings'
import { Route as featuresDiscoveryRoutesStartCategoryDetailRouteImport } from './../features/discovery/routes/start-category-detail'
import { Route as featuresModerationRoutesStartKickRouteImport } from './../features/moderation/routes/start-kick'
import { Route as featuresModerationRoutesStartTwitchRouteImport } from './../features/moderation/routes/start-twitch'
import { Route as featuresPlaybackRoutesStartStreamRouteImport } from './../features/playback/routes/start-stream'
import { Route as featuresPlaybackRoutesStartVideoRouteImport } from './../features/playback/routes/start-video'

const featuresShellRoutesStartLayoutRoute =
  featuresShellRoutesStartLayoutRouteImport.update({
    id: '/_app',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresDiscoveryRoutesStartHomeRoute =
  featuresDiscoveryRoutesStartHomeRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)
const featuresDiscoveryRoutesStartCategoriesRoute =
  featuresDiscoveryRoutesStartCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)
const featuresMediaLibraryRoutesStartDownloadsRoute =
  featuresMediaLibraryRoutesStartDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)
const featuresDiscoveryRoutesStartFollowingRoute =
  featuresDiscoveryRoutesStartFollowingRouteImport.update({
    id: '/following',
    path: '/following',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)
const featuresMediaLibraryRoutesStartHistoryRoute =
  featuresMediaLibraryRoutesStartHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)
const featuresModerationRoutesStartModRoute =
  featuresModerationRoutesStartModRouteImport.update({
    id: '/mod',
    path: '/mod',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)
const featuresMultistreamRoutesStartMultistreamRoute =
  featuresMultistreamRoutesStartMultistreamRouteImport.update({
    id: '/multistream',
    path: '/multistream',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)
const featuresDiscoveryRoutesStartSearchRoute =
  featuresDiscoveryRoutesStartSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)
const featuresSettingsRoutesStartSettingsRoute =
  featuresSettingsRoutesStartSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)
const featuresDiscoveryRoutesStartCategoryDetailRoute =
  featuresDiscoveryRoutesStartCategoryDetailRouteImport.update({
    id: '/categories/$platform/$categoryId',
    path: '/categories/$platform/$categoryId',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)
const featuresModerationRoutesStartKickRoute =
  featuresModerationRoutesStartKickRouteImport.update({
    id: '/mod/kick/$channel',
    path: '/mod/kick/$channel',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)
const featuresModerationRoutesStartTwitchRoute =
  featuresModerationRoutesStartTwitchRouteImport.update({
    id: '/mod/twitch/$channel',
    path: '/mod/twitch/$channel',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)
const featuresPlaybackRoutesStartStreamRoute =
  featuresPlaybackRoutesStartStreamRouteImport.update({
    id: '/stream/$platform/$channel',
    path: '/stream/$platform/$channel',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)
const featuresPlaybackRoutesStartVideoRoute =
  featuresPlaybackRoutesStartVideoRouteImport.update({
    id: '/video/$platform/$videoId',
    path: '/video/$platform/$videoId',
    getParentRoute: () => featuresShellRoutesStartLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof featuresDiscoveryRoutesStartHomeRoute
  '/categories': typeof featuresDiscoveryRoutesStartCategoriesRoute
  '/downloads': typeof featuresMediaLibraryRoutesStartDownloadsRoute
  '/following': typeof featuresDiscoveryRoutesStartFollowingRoute
  '/history': typeof featuresMediaLibraryRoutesStartHistoryRoute
  '/mod': typeof featuresModerationRoutesStartModRoute
  '/multistream': typeof featuresMultistreamRoutesStartMultistreamRoute
  '/search': typeof featuresDiscoveryRoutesStartSearchRoute
  '/settings': typeof featuresSettingsRoutesStartSettingsRoute
  '/categories/$platform/$categoryId': typeof featuresDiscoveryRoutesStartCategoryDetailRoute
  '/mod/kick/$channel': typeof featuresModerationRoutesStartKickRoute
  '/mod/twitch/$channel': typeof featuresModerationRoutesStartTwitchRoute
  '/stream/$platform/$channel': typeof featuresPlaybackRoutesStartStreamRoute
  '/video/$platform/$videoId': typeof featuresPlaybackRoutesStartVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof featuresDiscoveryRoutesStartHomeRoute
  '/categories': typeof featuresDiscoveryRoutesStartCategoriesRoute
  '/downloads': typeof featuresMediaLibraryRoutesStartDownloadsRoute
  '/following': typeof featuresDiscoveryRoutesStartFollowingRoute
  '/history': typeof featuresMediaLibraryRoutesStartHistoryRoute
  '/mod': typeof featuresModerationRoutesStartModRoute
  '/multistream': typeof featuresMultistreamRoutesStartMultistreamRoute
  '/search': typeof featuresDiscoveryRoutesStartSearchRoute
  '/settings': typeof featuresSettingsRoutesStartSettingsRoute
  '/categories/$platform/$categoryId': typeof featuresDiscoveryRoutesStartCategoryDetailRoute
  '/mod/kick/$channel': typeof featuresModerationRoutesStartKickRoute
  '/mod/twitch/$channel': typeof featuresModerationRoutesStartTwitchRoute
  '/stream/$platform/$channel': typeof featuresPlaybackRoutesStartStreamRoute
  '/video/$platform/$videoId': typeof featuresPlaybackRoutesStartVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof featuresShellRoutesStartLayoutRouteWithChildren
  '/_app/': typeof featuresDiscoveryRoutesStartHomeRoute
  '/_app/categories': typeof featuresDiscoveryRoutesStartCategoriesRoute
  '/_app/downloads': typeof featuresMediaLibraryRoutesStartDownloadsRoute
  '/_app/following': typeof featuresDiscoveryRoutesStartFollowingRoute
  '/_app/history': typeof featuresMediaLibraryRoutesStartHistoryRoute
  '/_app/mod': typeof featuresModerationRoutesStartModRoute
  '/_app/multistream': typeof featuresMultistreamRoutesStartMultistreamRoute
  '/_app/search': typeof featuresDiscoveryRoutesStartSearchRoute
  '/_app/settings': typeof featuresSettingsRoutesStartSettingsRoute
  '/_app/categories/$platform/$categoryId': typeof featuresDiscoveryRoutesStartCategoryDetailRoute
  '/_app/mod/kick/$channel': typeof featuresModerationRoutesStartKickRoute
  '/_app/mod/twitch/$channel': typeof featuresModerationRoutesStartTwitchRoute
  '/_app/stream/$platform/$channel': typeof featuresPlaybackRoutesStartStreamRoute
  '/_app/video/$platform/$videoId': typeof featuresPlaybackRoutesStartVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/downloads'
    | '/following'
    | '/history'
    | '/mod'
    | '/multistream'
    | '/search'
    | '/settings'
    | '/categories/$platform/$categoryId'
    | '/mod/kick/$channel'
    | '/mod/twitch/$channel'
    | '/stream/$platform/$channel'
    | '/video/$platform/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/downloads'
    | '/following'
    | '/history'
    | '/mod'
    | '/multistream'
    | '/search'
    | '/settings'
    | '/categories/$platform/$categoryId'
    | '/mod/kick/$channel'
    | '/mod/twitch/$channel'
    | '/stream/$platform/$channel'
    | '/video/$platform/$videoId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/categories'
    | '/_app/downloads'
    | '/_app/following'
    | '/_app/history'
    | '/_app/mod'
    | '/_app/multistream'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/categories/$platform/$categoryId'
    | '/_app/mod/kick/$channel'
    | '/_app/mod/twitch/$channel'
    | '/_app/stream/$platform/$channel'
    | '/_app/video/$platform/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  featuresShellRoutesStartLayoutRoute: typeof featuresShellRoutesStartLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof featuresShellRoutesStartLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof featuresDiscoveryRoutesStartHomeRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof featuresDiscoveryRoutesStartCategoriesRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
    '/_app/downloads': {
      id: '/_app/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof featuresMediaLibraryRoutesStartDownloadsRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
    '/_app/following': {
      id: '/_app/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof featuresDiscoveryRoutesStartFollowingRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof featuresMediaLibraryRoutesStartHistoryRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
    '/_app/mod': {
      id: '/_app/mod'
      path: '/mod'
      fullPath: '/mod'
      preLoaderRoute: typeof featuresModerationRoutesStartModRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
    '/_app/multistream': {
      id: '/_app/multistream'
      path: '/multistream'
      fullPath: '/multistream'
      preLoaderRoute: typeof featuresMultistreamRoutesStartMultistreamRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof featuresDiscoveryRoutesStartSearchRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof featuresSettingsRoutesStartSettingsRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
    '/_app/categories/$platform/$categoryId': {
      id: '/_app/categories/$platform/$categoryId'
      path: '/categories/$platform/$categoryId'
      fullPath: '/categories/$platform/$categoryId'
      preLoaderRoute: typeof featuresDiscoveryRoutesStartCategoryDetailRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
    '/_app/mod/kick/$channel': {
      id: '/_app/mod/kick/$channel'
      path: '/mod/kick/$channel'
      fullPath: '/mod/kick/$channel'
      preLoaderRoute: typeof featuresModerationRoutesStartKickRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
    '/_app/mod/twitch/$channel': {
      id: '/_app/mod/twitch/$channel'
      path: '/mod/twitch/$channel'
      fullPath: '/mod/twitch/$channel'
      preLoaderRoute: typeof featuresModerationRoutesStartTwitchRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
    '/_app/stream/$platform/$channel': {
      id: '/_app/stream/$platform/$channel'
      path: '/stream/$platform/$channel'
      fullPath: '/stream/$platform/$channel'
      preLoaderRoute: typeof featuresPlaybackRoutesStartStreamRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
    '/_app/video/$platform/$videoId': {
      id: '/_app/video/$platform/$videoId'
      path: '/video/$platform/$videoId'
      fullPath: '/video/$platform/$videoId'
      preLoaderRoute: typeof featuresPlaybackRoutesStartVideoRouteImport
      parentRoute: typeof featuresShellRoutesStartLayoutRoute
    }
  }
}

interface featuresShellRoutesStartLayoutRouteChildren {
  featuresDiscoveryRoutesStartHomeRoute: typeof featuresDiscoveryRoutesStartHomeRoute
  featuresDiscoveryRoutesStartCategoriesRoute: typeof featuresDiscoveryRoutesStartCategoriesRoute
  featuresMediaLibraryRoutesStartDownloadsRoute: typeof featuresMediaLibraryRoutesStartDownloadsRoute
  featuresDiscoveryRoutesStartFollowingRoute: typeof featuresDiscoveryRoutesStartFollowingRoute
  featuresMediaLibraryRoutesStartHistoryRoute: typeof featuresMediaLibraryRoutesStartHistoryRoute
  featuresModerationRoutesStartModRoute: typeof featuresModerationRoutesStartModRoute
  featuresMultistreamRoutesStartMultistreamRoute: typeof featuresMultistreamRoutesStartMultistreamRoute
  featuresDiscoveryRoutesStartSearchRoute: typeof featuresDiscoveryRoutesStartSearchRoute
  featuresSettingsRoutesStartSettingsRoute: typeof featuresSettingsRoutesStartSettingsRoute
  featuresDiscoveryRoutesStartCategoryDetailRoute: typeof featuresDiscoveryRoutesStartCategoryDetailRoute
  featuresModerationRoutesStartKickRoute: typeof featuresModerationRoutesStartKickRoute
  featuresModerationRoutesStartTwitchRoute: typeof featuresModerationRoutesStartTwitchRoute
  featuresPlaybackRoutesStartStreamRoute: typeof featuresPlaybackRoutesStartStreamRoute
  featuresPlaybackRoutesStartVideoRoute: typeof featuresPlaybackRoutesStartVideoRoute
}

const featuresShellRoutesStartLayoutRouteChildren: featuresShellRoutesStartLayoutRouteChildren =
  {
    featuresDiscoveryRoutesStartHomeRoute:
      featuresDiscoveryRoutesStartHomeRoute,
    featuresDiscoveryRoutesStartCategoriesRoute:
      featuresDiscoveryRoutesStartCategoriesRoute,
    featuresMediaLibraryRoutesStartDownloadsRoute:
      featuresMediaLibraryRoutesStartDownloadsRoute,
    featuresDiscoveryRoutesStartFollowingRoute:
      featuresDiscoveryRoutesStartFollowingRoute,
    featuresMediaLibraryRoutesStartHistoryRoute:
      featuresMediaLibraryRoutesStartHistoryRoute,
    featuresModerationRoutesStartModRoute:
      featuresModerationRoutesStartModRoute,
    featuresMultistreamRoutesStartMultistreamRoute:
      featuresMultistreamRoutesStartMultistreamRoute,
    featuresDiscoveryRoutesStartSearchRoute:
      featuresDiscoveryRoutesStartSearchRoute,
    featuresSettingsRoutesStartSettingsRoute:
      featuresSettingsRoutesStartSettingsRoute,
    featuresDiscoveryRoutesStartCategoryDetailRoute:
      featuresDiscoveryRoutesStartCategoryDetailRoute,
    featuresModerationRoutesStartKickRoute:
      featuresModerationRoutesStartKickRoute,
    featuresModerationRoutesStartTwitchRoute:
      featuresModerationRoutesStartTwitchRoute,
    featuresPlaybackRoutesStartStreamRoute:
      featuresPlaybackRoutesStartStreamRoute,
    featuresPlaybackRoutesStartVideoRoute:
      featuresPlaybackRoutesStartVideoRoute,
  }

const featuresShellRoutesStartLayoutRouteWithChildren =
  featuresShellRoutesStartLayoutRoute._addFileChildren(
    featuresShellRoutesStartLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  featuresShellRoutesStartLayoutRoute:
    featuresShellRoutesStartLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './start-router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
